### ISSUE TITLE
Bad link to User Guide on developer site

### ISSUE THREAD

**Issue by thejta** [amd/esmi_oob_library#4]
There is an issue with the links to the Users Guide on https://developer.amd.com/e-sms/apml-library/ - they point to a file that no longer exists on github.

There are two links with this problem, the "User Guide" near the upper right hand area of the page and under the Resources and Technical Support section near the bottom.

I'm guessing those links should perhaps point now to here: https://github.com/amd/esmi_oob_library/blob/master/APML_Library_Manual.pdf

**Comment by nchatrad** [comment]
Will correct it. thanks for pointing out

**Comment by nchatrad** [comment]
All the links are corrected. thanks Jason.
